# Generated by Django 4.0.2 on 2022-08-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0015_factions'),
        ('ghosttools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghosttoolsconfiguration',
            name='corporations',
        ),
        migrations.AddField(
            model_name='ghosttoolsconfiguration',
            name='corporation',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecorporationinfo'),
        ),
    ]
