# Generated by Django 4.0.2 on 2022-08-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corptools', '0076_remove_characterasset_corptools_c_type_id_05ccc2_idx_and_more'),
        ('ghosttools', '0002_remove_ghosttoolsconfiguration_corporations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghosttoolsconfiguration',
            name='stagings',
            field=models.ManyToManyField(
                blank=True, to='corptools.EveLocation'),
        ),
    ]
