# Generated by Django 4.0.2 on 2022-09-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0015_factions'),
        ('ghosttools', '0003_ghosttoolsconfiguration_stagings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghosttoolsconfiguration',
            name='alliances',
            field=models.ManyToManyField(
                blank=True, to='eveonline.EveAllianceInfo'),
        ),
    ]
