# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  create:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install -g yarn
      - name: install dependencies
        if: ${{ !env.ACT }}
        run: make dev
      - name: Run Tests
        if: ${{ !env.ACT }}
        run: make test
      - name: Upload test coverage
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: Python3.9 Test Coverage
          # A file, directory or wildcard pattern that describes what to upload
          path: htmlcov/
      - name: Build Node
        run: make packagejs
      - name: Build Python
        run: make packagepy
      - name: Uploade Package
        run: make deploy
